name: Build,Analyze,scan
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-Latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run test
        run: echo "This is self Build of github action code"
 
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run test
        run: echo "This is self test of github action code"
  
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run deploy
        run: echo "This is Deploy of github action code"
        